name: CI
on:
  workflow_dispatch:
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]

#permissions:
#  contents: read
#  actions: read
#  checks: write
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run tests
        run: |
          echo "✅ Tests passed"
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
